name: Security Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          args: --only-verified --fail

      - name: Check for AWS credentials
        run: |
          if grep -r "AKIA[0-9A-Z]{16}" .; then
            echo "❌ AWS Access Key found in code"
            exit 1
          fi

      - name: Check for AWS exports
        run: |
          if find . -name "aws-exports.*"; then
            echo "❌ AWS exports files found"
            exit 1
          fi
